export const STREAMS = [
  {
    id: "cse",
    code: "CSE",
    name: "Computer Science",
    tagline: "Build the software that runs civilization.",
    icon: "⌨",
    color: "#4a9eff",
    colorRgb: "74,158,255",
    tags: ["Software", "Systems", "Web"],
    description:
      "From operating systems to full-stack apps — CSE is the engine room of every digital product on the planet.",
    particles: [
      { sym: "{}", x: "10%", y: "20%", delay: 0, dur: 6, size: "1.1rem" },
      { sym: "</>", x: "80%", y: "15%", delay: 1.2, dur: 7, size: "0.9rem" },
      { sym: "fn", x: "60%", y: "70%", delay: 0.5, dur: 5, size: "0.8rem" },
      { sym: "[]", x: "20%", y: "75%", delay: 2, dur: 8, size: "0.9rem" },
      { sym: "=>", x: "50%", y: "40%", delay: 0.8, dur: 6.5, size: "0.7rem" },
    ],
    learn: [
      "Data Structures & Algorithms",
      "Operating Systems & Computer Networks",
      "Database Management & SQL",
      "Software Engineering & Design Patterns",
      "Web Development (Frontend + Backend)",
      "Cloud Computing & DevOps",
      "Compiler Design & System Programming",
    ],
    futureTech: [
      { icon: "🧠", name: "AI Engineering" },
      { icon: "☁️", name: "Cloud Native" },
      { icon: "🔐", name: "Cybersecurity" },
      { icon: "⛓", name: "Blockchain" },
      { icon: "🤖", name: "Robotics Software" },
      { icon: "🌐", name: "Web3" },
      { icon: "📱", name: "Mobile Platforms" },
      { icon: "🎮", name: "Game Engines" },
    ],
    demand: {
      summary:
        "CSE graduates are the most sought-after globally. Every industry — from healthcare to finance — runs on software. Demand consistently outpaces supply.",
      stats: [
        { val: "#1", label: "Hiring Rate" },
        { val: "40%", label: "5-yr Job Growth" },
        { val: "Global", label: "Remote Reach" },
      ],
    },
    skills: [
      { icon: "🔢", text: "Logical & mathematical thinking" },
      { icon: "🧩", text: "Problem-solving mindset" },
      { icon: "🏗", text: "Love for building and creating" },
      { icon: "📖", text: "Continuous learning drive" },
    ],
    salary: {
      tiers: [
        { level: "Entry", range: "₹4–10 LPA", pct: 35 },
        { level: "Mid", range: "₹12–25 LPA", pct: 65 },
        { level: "Senior", range: "₹30–60 LPA", pct: 85 },
        { level: "Staff+", range: "₹60L–1Cr+", pct: 100 },
      ],
      note: "CSE roles at product companies offer among the highest compensation in tech globally.",
    },
  },
  {
    id: "ece",
    code: "ECE",
    name: "Electronics & Comm.",
    tagline: "Engineer the hardware that powers everything.",
    icon: "⚡",
    color: "#f4b942",
    colorRgb: "244,185,66",
    tags: ["Circuits", "Embedded", "RF"],
    description:
      "ECE sits at the intersection of hardware and software — from designing chips to building wireless communication systems.",
    particles: [
      { sym: "∿", x: "15%", y: "25%", delay: 0, dur: 6, size: "1.2rem" },
      { sym: "⊕", x: "75%", y: "20%", delay: 1, dur: 7, size: "1rem" },
      { sym: "Ω", x: "55%", y: "65%", delay: 0.4, dur: 5, size: "1rem" },
      { sym: "±", x: "25%", y: "70%", delay: 1.8, dur: 8, size: "0.9rem" },
      { sym: "∏", x: "45%", y: "35%", delay: 0.7, dur: 6, size: "0.8rem" },
    ],
    learn: [
      "Analog & Digital Electronics",
      "Signal Processing & Communication Systems",
      "VLSI Design & Semiconductor Physics",
      "Embedded Systems & Microcontrollers",
      "Antenna Design & RF Engineering",
      "Control Systems & Instrumentation",
      "PCB Design & Hardware Prototyping",
    ],
    futureTech: [
      { icon: "📡", name: "5G / 6G" },
      { icon: "🔬", name: "Nanotechnology" },
      { icon: "🤖", name: "Embedded AI" },
      { icon: "🛰", name: "Satellite Systems" },
      { icon: "💡", name: "IoT Devices" },
      { icon: "⚡", name: "Power Electronics" },
      { icon: "🧬", name: "Bio-Electronics" },
      { icon: "🖥", name: "FPGA / ASIC" },
    ],
    demand: {
      summary:
        "With IoT, 5G rollout, and semiconductor sovereignty becoming national priorities, ECE engineers are critical infrastructure builders.",
      stats: [
        { val: "SEMI", label: "Boom Industry" },
        { val: "2×", label: "IoT Growth" },
        { val: "Core", label: "Defence & Space" },
      ],
    },
    skills: [
      { icon: "⚡", text: "Fascination with circuits and electronics" },
      { icon: "🔭", text: "Interest in physics and signals" },
      { icon: "🔧", text: "Hands-on hardware tinkering" },
      { icon: "📐", text: "Precision and analytical thinking" },
    ],
    salary: {
      tiers: [
        { level: "Entry", range: "₹3–8 LPA", pct: 30 },
        { level: "Mid", range: "₹10–20 LPA", pct: 58 },
        { level: "Senior", range: "₹22–45 LPA", pct: 78 },
        { level: "Expert", range: "₹50L+", pct: 92 },
      ],
      note: "VLSI, chip design, and semiconductor roles command premium salaries globally.",
    },
  },
  {
    id: "aiml",
    code: "AIML",
    name: "AI & Machine Learning",
    tagline: "Teach machines to think, reason, and create.",
    icon: "🧠",
    color: "#a78bfa",
    colorRgb: "167,139,250",
    tags: ["Neural Nets", "NLP", "Vision"],
    description:
      "The most transformative field of our era. AIML engineers design systems that learn, adapt, and generate — from GPT to medical diagnostics.",
    particles: [
      { sym: "◉", x: "12%", y: "22%", delay: 0, dur: 6, size: "1rem" },
      { sym: "∞", x: "78%", y: "18%", delay: 1.1, dur: 7, size: "1.1rem" },
      { sym: "λ", x: "58%", y: "68%", delay: 0.5, dur: 5, size: "1rem" },
      { sym: "∂", x: "28%", y: "72%", delay: 2, dur: 8, size: "0.9rem" },
      { sym: "∑", x: "48%", y: "38%", delay: 0.9, dur: 6, size: "1.2rem" },
    ],
    learn: [
      "Linear Algebra, Probability & Statistics",
      "Machine Learning Algorithms",
      "Deep Learning & Neural Networks",
      "Natural Language Processing (NLP)",
      "Computer Vision & Image Recognition",
      "Reinforcement Learning",
      "MLOps & Model Deployment at Scale",
    ],
    futureTech: [
      { icon: "🤖", name: "AGI Research" },
      { icon: "🎨", name: "Generative AI" },
      { icon: "🏥", name: "Medical AI" },
      { icon: "🚗", name: "Autonomous Vehicles" },
      { icon: "🗣", name: "Voice AI" },
      { icon: "🔬", name: "Drug Discovery AI" },
      { icon: "📊", name: "Quantitative Finance" },
      { icon: "🌐", name: "AI Agents" },
    ],
    demand: {
      summary:
        "AI/ML is the fastest-growing field in tech. Every industry is racing to integrate intelligent systems. Talent demand far exceeds current supply.",
      stats: [
        { val: "×5", label: "Job Growth" },
        { val: "Every", label: "Industry Vertical" },
        { val: "Global", label: "Research Roles" },
      ],
    },
    skills: [
      { icon: "📊", text: "Strong mathematical foundation" },
      { icon: "🧪", text: "Scientific curiosity & experimentation" },
      { icon: "💡", text: "Pattern recognition thinking" },
      { icon: "📚", text: "Appetite for research papers" },
    ],
    salary: {
      tiers: [
        { level: "Entry", range: "₹6–14 LPA", pct: 40 },
        { level: "Mid", range: "₹18–35 LPA", pct: 68 },
        { level: "Senior", range: "₹40–80 LPA", pct: 90 },
        { level: "Research", range: "₹1Cr+", pct: 100 },
      ],
      note: "AI researchers and senior ML engineers at FAANG and AI labs are among the highest-paid professionals worldwide.",
    },
  },
  {
    id: "mech",
    code: "MECH",
    name: "Mechanical Eng.",
    tagline: "Design the physical world with precision.",
    icon: "⚙",
    color: "#34d399",
    colorRgb: "52,211,153",
    tags: ["CAD", "Thermal", "Robotics"],
    description:
      "Mechanical engineering forms the backbone of manufacturing, aerospace, and robotics — now merging with software to create smart machines.",
    particles: [
      { sym: "⚙", x: "14%", y: "24%", delay: 0, dur: 8, size: "1.1rem" },
      { sym: "△", x: "76%", y: "18%", delay: 1.2, dur: 7, size: "0.9rem" },
      { sym: "⊗", x: "56%", y: "66%", delay: 0.6, dur: 6, size: "1rem" },
      { sym: "≡", x: "26%", y: "74%", delay: 1.8, dur: 9, size: "0.8rem" },
      { sym: "⊞", x: "46%", y: "36%", delay: 0.4, dur: 7, size: "0.9rem" },
    ],
    learn: [
      "Engineering Mechanics & Thermodynamics",
      "Fluid Mechanics & Heat Transfer",
      "Manufacturing Processes & CNC Machining",
      "CAD / CAM Design (SolidWorks, AutoCAD)",
      "Finite Element Analysis (FEA)",
      "Robotics & Mechatronics",
      "Automobile & Aerospace Engineering",
    ],
    futureTech: [
      { icon: "🤖", name: "Collaborative Robots" },
      { icon: "🚀", name: "Aerospace Systems" },
      { icon: "🔋", name: "EV Powertrains" },
      { icon: "🏭", name: "Smart Manufacturing" },
      { icon: "🌬", name: "Green Energy" },
      { icon: "🖨", name: "3D Printing" },
      { icon: "🛸", name: "Drone Systems" },
      { icon: "🧲", name: "Advanced Materials" },
    ],
    demand: {
      summary:
        "EV revolution, aerospace expansion, and Industry 4.0 are transforming mechanical engineering into a high-tech discipline with global demand.",
      stats: [
        { val: "EV", label: "Sector Boom" },
        { val: "Core", label: "Manufacturing" },
        { val: "PSU", label: "Govt Opportunities" },
      ],
    },
    skills: [
      { icon: "🔧", text: "Love for physical systems and machines" },
      { icon: "📐", text: "Spatial reasoning and 3D thinking" },
      { icon: "🔬", text: "Interest in materials and properties" },
      { icon: "⚙", text: "Systematic problem-solving approach" },
    ],
    salary: {
      tiers: [
        { level: "Entry", range: "₹3–7 LPA", pct: 28 },
        { level: "Mid", range: "₹8–18 LPA", pct: 55 },
        { level: "Senior", range: "₹20–40 LPA", pct: 72 },
        { level: "Expert", range: "₹45L+", pct: 85 },
      ],
      note: "Specialising in robotics, EV, or aerospace can significantly elevate salaries to match software peers.",
    },
  },
  {
    id: "civil",
    code: "CIVIL",
    name: "Civil Engineering",
    tagline: "Build the infrastructure civilization depends on.",
    icon: "🏗",
    color: "#fb923c",
    colorRgb: "251,146,60",
    tags: ["Structures", "Urban", "Infra"],
    description:
      "Civil engineers design and build systems that support life — roads, bridges, smart cities, water networks, and climate-resilient infrastructure.",
    particles: [
      { sym: "△", x: "16%", y: "22%", delay: 0, dur: 7, size: "1rem" },
      { sym: "⬡", x: "74%", y: "20%", delay: 1, dur: 8, size: "1.1rem" },
      { sym: "□", x: "54%", y: "68%", delay: 0.5, dur: 6, size: "0.9rem" },
      { sym: "⬟", x: "30%", y: "76%", delay: 2, dur: 9, size: "0.8rem" },
      { sym: "⊞", x: "44%", y: "34%", delay: 0.8, dur: 7, size: "0.9rem" },
    ],
    learn: [
      "Structural Analysis & Design",
      "Geotechnical Engineering & Soil Mechanics",
      "Fluid Mechanics & Hydraulics",
      "Construction Management & Planning",
      "Transportation & Urban Planning",
      "Environmental Engineering",
      "BIM (Building Information Modeling)",
    ],
    futureTech: [
      { icon: "🌆", name: "Smart Cities" },
      { icon: "🌱", name: "Green Buildings" },
      { icon: "💧", name: "Water Systems" },
      { icon: "🤖", name: "Construction Robots" },
      { icon: "🛰", name: "GIS & Remote Sensing" },
      { icon: "🖥", name: "BIM & Digital Twin" },
      { icon: "🌊", name: "Coastal Engineering" },
      { icon: "☀️", name: "Renewable Infra" },
    ],
    demand: {
      summary:
        "With India's massive infrastructure push and global smart city initiatives, civil engineers with digital skills are in exceptional demand.",
      stats: [
        { val: "₹100T", label: "Infra Pipeline" },
        { val: "PSU+", label: "Govt & Private" },
        { val: "Global", label: "Construction Boom" },
      ],
    },
    skills: [
      { icon: "🏗", text: "Visual and structural spatial thinking" },
      { icon: "📏", text: "Precision and attention to detail" },
      { icon: "🌍", text: "Interest in environmental impact" },
      { icon: "👥", text: "Project & team leadership ability" },
    ],
    salary: {
      tiers: [
        { level: "Entry", range: "₹3–6 LPA", pct: 25 },
        { level: "Mid", range: "₹8–16 LPA", pct: 50 },
        { level: "Senior", range: "₹18–35 LPA", pct: 68 },
        { level: "Director", range: "₹40L+", pct: 80 },
      ],
      note: "Structural engineers and project directors in international markets command significantly higher packages.",
    },
  },
  {
    id: "ds",
    code: "DS",
    name: "Data Science",
    tagline: "Turn raw data into decisions that shape the future.",
    icon: "📊",
    color: "#2dd4bf",
    colorRgb: "45,212,191",
    tags: ["Analytics", "Viz", "Stats"],
    description:
      "Data Scientists extract meaning from vast, complex datasets to drive strategy, predict outcomes, and create competitive advantages.",
    particles: [
      { sym: "∑", x: "13%", y: "23%", delay: 0, dur: 6, size: "1.1rem" },
      { sym: "μ", x: "77%", y: "17%", delay: 1.1, dur: 7, size: "1rem" },
      { sym: "σ", x: "57%", y: "67%", delay: 0.4, dur: 5, size: "1rem" },
      { sym: "∫", x: "27%", y: "73%", delay: 1.9, dur: 8, size: "0.9rem" },
      { sym: "χ", x: "47%", y: "37%", delay: 0.7, dur: 6, size: "1.1rem" },
    ],
    learn: [
      "Statistics, Probability & Linear Algebra",
      "Python & R for Data Analysis",
      "Data Wrangling & Feature Engineering",
      "Machine Learning for Predictive Models",
      "Data Visualization (Tableau, Power BI)",
      "Big Data Technologies (Spark, Hadoop)",
      "Business Intelligence & Analytics Strategy",
    ],
    futureTech: [
      { icon: "⚡", name: "Real-time Analytics" },
      { icon: "🧬", name: "Genomics Data" },
      { icon: "🏦", name: "FinTech Analytics" },
      { icon: "🌐", name: "Graph Analytics" },
      { icon: "🤖", name: "AutoML Platforms" },
      { icon: "🛒", name: "Recommendation AI" },
      { icon: "🏥", name: "Clinical Data Science" },
      { icon: "📡", name: "Streaming Pipelines" },
    ],
    demand: {
      summary:
        "Data is the new oil. Organizations of every scale are investing in data teams. The ability to extract business value from data is uniquely powerful.",
      stats: [
        { val: "×4", label: "Role Growth" },
        { val: "All", label: "Sectors Need It" },
        { val: "High", label: "Hybrid Premium" },
      ],
    },
    skills: [
      { icon: "📊", text: "Love for patterns, numbers, and trends" },
      { icon: "🧩", text: "Curiosity-driven analytical mindset" },
      { icon: "💬", text: "Strong data storytelling instinct" },
      { icon: "🏢", text: "Interest in business strategy" },
    ],
    salary: {
      tiers: [
        { level: "Analyst", range: "₹5–10 LPA", pct: 35 },
        { level: "Scientist", range: "₹14–28 LPA", pct: 62 },
        { level: "Senior", range: "₹30–55 LPA", pct: 82 },
        { level: "Lead", range: "₹60L–1Cr", pct: 95 },
      ],
      note: "Data Science roles in product companies and finance offer highly competitive compensation with rapid progression.",
    },
  },
];
